# Default values for 9c-main cluster.
# This is a YAML-formatted file.

clusterName: "9c-main-v2"
logLevel: "debug"

global:
  image:
    repository: planetariumhq/ninechronicles-headless
    tag: "60"

  appProtocolVersion: "200090/AB2da648b9154F2cCcAFBD85e0Bc3d51f97330Fc/MEUCIQDq8LsVGQqdTFnr7E6wVZYaYGBoYtITrm2CSPglPLEjOwIgMYKTwbR5uwkn+1xucHCffUnQicsTjkZbJH9GV23IjIs=/ZHU5OnRpbWVzdGFtcHUxMDoyMDIzLTEwLTA2ZQ=="
  genesisBlockPath: "https://release.nine-chronicles.com/genesis-block-9c-main"
  trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

  peerStrings:
  - "027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31234"
  - "02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31234"
  - "0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31234"

  iceServers:
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us2.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us3.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us4.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us5.planetarium.dev:3478"

  networkType: Main
  consensusType: pbft

  resetSnapshot: false
  rollbackSnapshot: false
  useExternalSecret: true

snapshot:
  slackChannel: "9c-mainnet"
  image: "planetariumhq/ninechronicles-snapshot:git-c3669931b652f49b8b38e111c0f2c51619e436d4"
  path: "main/partition"

  fullSnapshot:
    enabled: true
    suspend: false

  partitionReset:
    enabled: true

  partition:
    enabled: true

  nodeSelector:
    node.kubernetes.io/instance-type: r6g.xlarge

# if you want to delete PVC with the volume provisioned together, set this value "Delete"
volumeReclaimPolicy: "Retain"

seed:
  count: 3
  useTurnServer: false
  image:
    tag: "git-22bed8ef41ab09258e6404462ec8e07cd038d089"

  hosts:
  - "9c-main-tcp-seed-1.planetarium.dev"
  - "9c-main-tcp-seed-2.planetarium.dev"
  - "9c-main-tcp-seed-3.planetarium.dev"

  loggingEnabled: true

  # dotnet args
  workerCount: 1000

  nodeSelector:
    node.kubernetes.io/instance-type: m5.large

validator:
  count: 4

  env:
  - name: IpRateLimiting__EnableEndpointRateLimiting
    value: "true"
  - name: IpRateLimiting__GeneralRules__2__Endpoint
    value: "*:/graphql"
  - name: IpRateLimiting__GeneralRules__2__Period
    value: 1s
  - name: IpRateLimiting__GeneralRules__2__Limit
    value: "10"
  - name: IpRateLimiting__IpBanMinute
    value: "30"
  - name: IpRateLimiting__IpWhiteList__1
    value: "::ffff:3.18.248.125"
  - name: IpRateLimiting__IpWhiteList__2
    value: "::ffff:13.124.239.97"
  - name: IpRateLimiting__IpWhiteList__3
    value: "::ffff:118.131.110.197"

  loggingEnabled: true

  extraArgs:
  - --tx-quota-per-signer=1
  - --consensus-target-block-interval=8500

  consensusSeedStrings:
  - "027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31235"
  - "02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31235"
  - "0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31235"

  hosts:
  - "9c-main-validator-5.nine-chronicles.com"
  - "9c-main-validator-6.nine-chronicles.com"
  - "9c-main-validator-7.nine-chronicles.com"
  - "9c-main-validator-8.nine-chronicles.com"

  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: validator-test

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-main-m7g_2xl_2c_validator

remoteHeadless:
  count: 3

  useTurnServer: false

  hosts:
  - "9c-main-rpc-1.nine-chronicles.com"
  - "9c-main-rpc-2.nine-chronicles.com"
  - "9c-main-rpc-3.nine-chronicles.com"
  - "9c-main-rpc-4.nine-chronicles.com"
  - "9c-main-rpc-5.nine-chronicles.com"
  - "9c-main-rpc-6.nine-chronicles.com"
  - "9c-main-rpc-7.nine-chronicles.com"
  - "9c-main-rpc-8.nine-chronicles.com"
  - "9c-main-rpc-9.nine-chronicles.com"
  - "9c-main-rpc-10.nine-chronicles.com"

  env:
  - name: IpRateLimiting__EnableEndpointRateLimiting
    value: "true"
  - name: IpRateLimiting__GeneralRules__0__Period
    value: "60s"
  - name: IpRateLimiting__GeneralRules__0__Limit
    value: "12"
  - name: IpRateLimiting__GeneralRules__1__Period
    value: "300s"
  - name: IpRateLimiting__GeneralRules__1__Limit
    value: "10"
  - name: MultiAccountManaging__EnableManaging
    value: "true"
  - name: IpRateLimiting__IpWhiteList__1
    value: "::ffff:3.18.248.125"
  - name: IpRateLimiting__IpWhiteList__2
    value: "::ffff:13.124.239.97"
  - name: IpRateLimiting__IpWhiteList__3
    value: "::ffff:118.131.110.197"

  extraArgs:
  - --sentry-dsn=https://625a444555a547e8822ee86d4f38f046@o195672.ingest.sentry.io/6197051
  - --sentry-trace-sample-rate=0.5
  - --tx-quota-per-signer=1

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-main-m7g_2xl_2c_test

  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: remote-headless-test

  loggingEnabled: true

dataProvider:
  enabled: true
  rwMode: true
  render: true

  image:
    repository: planetariumhq/ninechronicles-dataprovider
    pullPolicy: Always
    tag: '60'

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-main-m7g_xl_2c

  resources:
    requests:
      cpu: '3'
      memory: 12Gi

explorer:
  enabled: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always

  loggingEnabled: true

  extraArgs:
  - --tx-quota-per-signer=1

  nodeSelector:
    node.kubernetes.io/instance-type: r7g.xlarge

marketService:
  enabled: true
  rwMode: true
  image:
    tag: "git-68e6bc82786506b6c89e71f78bafc8d9bed3f23c"

  env:
  - name: DOTNET_gcServer
    value: "1"
  - name: RpcConfig__Host
    value: 9c-main-rpc-3.nine-chronicles.com
  - name: RpcConfig__Port
    value: "31238"
  - name: WorkerConfig__SyncShop
    value: "false"
  - name: WorkerConfig__SyncProduct
    value: "false"

  envForWrite:
  - name: DOTNET_gcServer
    value: "1"
  - name: RpcConfig__Host
    value: 9c-main-rpc-3.nine-chronicles.com
  - name: RpcConfig__Port
    value: "31238"
  - name: WorkerConfig__SyncShop
    value: "true"
  - name: WorkerConfig__SyncProduct
    value: "true"

  nodeSelector:
    read:
      node.kubernetes.io/instance-type: m5.large
    write:
      eks.amazonaws.com/nodegroup: 9c-main-m7g_xl_2c

fullState:
  enabled: true

  loggingEnabled: true

  useTurnServer: false

  host: "9c-main-full-state.nine-chronicles.com"

  extraArgs:
  - --no-reduce-store
  - --tx-quota-per-signer=1

  env:
  - name: IpRateLimiting__EnableEndpointRateLimiting
    value: "false"
  - name: IpRateLimiting__GeneralRules__0__Period
    value: "60s"
  - name: IpRateLimiting__GeneralRules__0__Limit
    value: "12"
  - name: IpRateLimiting__GeneralRules__1__Period
    value: "60s"
  - name: IpRateLimiting__GeneralRules__1__Limit
    value: "120"
  - name: IpRateLimiting__IpWhiteList__1
    value: "::ffff:157.245.68.243"
  - name: IpRateLimiting__IpWhiteList__2
    value: "::1"
  - name: IpRateLimiting__IpWhiteList__3
    value: "::ffff:172.70.126.138"
  - name: IpRateLimiting__IpWhiteList__4
    value: "::ffff:3.18.248.125"

  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: remote-headless-test

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-main-m7g_2xl_2c_test

worldBoss:
  enabled: true

  image:
    tag: "git-05ffdb0f2af019486b3213431031bca5e86a4a3d"

  nodeSelector:
    node.kubernetes.io/instance-type: m5.large

bridge:
  enabled: true
  bridgeObserverImage:
    tag: "git-da9637c9ee56051a252f11ff639ed2f0d674afc6"
  bridgeStatusBotImage:
    tag: "20210913-01"
  nodeSelector:
    node.kubernetes.io/instance-type: m5.large

testHeadless1:
  enabled: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    tag: "60"

  loggingEnabled: true

  host: "9c-main-test-1.nine-chronicles.com"

  env:
  - name: IpRateLimiting__EnableEndpointRateLimiting
    value: "true"
  - name: IpRateLimiting__GeneralRules__0__Period
    value: "60s"
  - name: IpRateLimiting__GeneralRules__0__Limit
    value: "12"
  - name: IpRateLimiting__GeneralRules__1__Period
    value: "60s"
  - name: IpRateLimiting__GeneralRules__1__Limit
    value: "12"

  extraArgs:
  - --tx-quota-per-signer=1
  - --config=appsettings.configmap.json

  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: remote-headless-test

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-main-m7g_2xl_2c_test

testHeadless2:
  enabled: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    tag: "60"

  loggingEnabled: true

  env:
  - name: IpRateLimiting__EnableEndpointRateLimiting
    value: "true"
  - name: IpRateLimiting__GeneralRules__0__Period
    value: "60s"
  - name: IpRateLimiting__GeneralRules__0__Limit
    value: "12"
  - name: IpRateLimiting__GeneralRules__1__Period
    value: "60s"
  - name: IpRateLimiting__GeneralRules__1__Limit
    value: "12"

  extraArgs:
  - --tx-quota-per-signer=1

  host: "9c-main-test-2.nine-chronicles.com"

  resources:
    requests:
      cpu: 2
      memory: 20Gi

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-main-r6g_xl_2c

emptyChronicle:
  enabled: true

  image:
    tag: "git-7bef02eb0105de7c14741e45282c63c7b40c70fb"

remoteActionEvaluatorHeadless:
  enabled: true
  image:
    tag: "41"

  loggingEnabled: true

  useTurnServer: true

  host: "9c-main-remote-aev-test.nine-chronicles.com"

  extraArgs:
  - --tx-quota-per-signer=1

  nodeSelector:
    eks.amazonaws.com/nodegroup: 9c-main-r7g_xl_2c

blockIntervalNotifier:
  enabled: true

patrolRewardService:
  enabled: true
  image:
    repository: planetariumhq/patrol-reward-service
    pullPolicy: Always
    tag: "git-f359def75d6b20313b67e2dfc3e1d024d558299a"

  nodeSelector:
    node.kubernetes.io/instance-type: m5.large
