# Default values for libplanet-seed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterName: "9c-main-v2"
logLevel: "debug"
appProtocolVersion: "200060/AB2da648b9154F2cCcAFBD85e0Bc3d51f97330Fc/MEQCIBqT.MLqhi8PWIoNdRqwVrVw+YEYJKbwqZkCUcyLB4O8AiB8z0qhNbnoKaT94vgOt5kYAxZIL6Z1uwJ3MdXrehXfRQ==/ZHU5OnRpbWVzdGFtcHUxMDoyMDIzLTA4LTIyZQ=="
genesisBlockPath: "https://release.nine-chronicles.com/genesis-block-9c-main"
trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

peerStrings:
- "027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31234"
- "02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31234"
- "0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31234"

iceServers:
- "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478"
- "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us2.planetarium.dev:3478"
- "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us3.planetarium.dev:3478"
- "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us4.planetarium.dev:3478"
- "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us5.planetarium.dev:3478"

networkType: Main
consensusType: pbft

useExternalSecret: true
slackToken: ""
slackWebHookUrl: ""

snapshot:
  resetSnapshot: false
  slackChannel: "9c-mainnet"
  image: "planetariumhq/ninechronicles-snapshot:git-c3669931b652f49b8b38e111c0f2c51619e436d4"

  # aws information for uploading snapshot
  # Do not upload values below filled
  # recommended to obtain from ExternalSecret
  cfDistributionId: ""
  aws_access_key_id: ""
  aws_secret_access_key: ""

# if you want to delete PVC with the volume provisioned together, set this value "Delete"
volumeReclaimPolicy: "Retain"

seed:
  count: 3
  useTurnServer: false
  image:
    repository: planetariumhq/libplanet-seed
    pullPolicy: Always # Overrides the image tag whose default is the chart appVersion.
    tag: "git-22bed8ef41ab09258e6404462ec8e07cd038d089"

  hosts:
  - "9c-main-tcp-seed-1.planetarium.dev"
  - "9c-main-tcp-seed-2.planetarium.dev"
  - "9c-main-tcp-seed-3.planetarium.dev"

  ports:
    node: 31234
    gossip: 31235
    graphql: 31237

  # dotnet args
  workerCount: 1000

  extraArgs: []
  # - --key=val

  # enter private keys if not using External Secrets
  privateKeys: []
  # - "private key"

  env: []

  resources:
    requests:
      cpu: 1

  nodeSelector: {}
  tolerations: []
  affinity: {}

miner:
  count: 1
  useTurnServer: false

  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-5fffd9a94eac89305cadca9d0fb958ce460f7c69"

  # host domains if not using turn servers
  hosts: []
  #  - "a7e209d2837b94a9db601e3f7385daf5-1493908636.us-east-2.elb.amazonaws.com"

  ports:
    headless: 31234
    graphql: 80

  # dotnet args

  extraArgs: []
  # - --key=val

  # private keys if not using External Secrets
  privateKeys: []
  # - "private key"

  storage:
    data: 1000Gi

  env: []

  resources:
    requests:
      cpu: 2
      memory: 20Gi

  nodeSelector: {}
  tolerations: []
  affinity: {}

remoteHeadless:
  count: 3
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-5fffd9a94eac89305cadca9d0fb958ce460f7c69"

  # dotnet args

  extraArgs: []
  # - --key=val

  useTurnServer: false

  hosts:
  - "9c-main-rpc-1.nine-chronicles.com"
  - "9c-main-rpc-2.nine-chronicles.com"
  - "9c-main-rpc-3.nine-chronicles.com"
  - "9c-main-rpc-4.nine-chronicles.com"
  - "9c-main-rpc-5.nine-chronicles.com"
  - "9c-main-rpc-6.nine-chronicles.com"
  - "9c-main-rpc-7.nine-chronicles.com"
  - "9c-main-rpc-8.nine-chronicles.com"
  - "9c-main-rpc-9.nine-chronicles.com"
  - "9c-main-rpc-10.nine-chronicles.com"

  ports:
    headless: 31234
    graphql: 80
    rpc: 31238

  storage:
    data: 1000Gi

  resources:
    requests:
      cpu: 2
      memory: 20Gi

  nodeSelector:
    beta.kubernetes.io/os: linux
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "remote-headless-test"
    effect: "NoSchedule"
  affinity: {}

emptyChronicle:
  enabled: true

  image:
    repository: planetariumhq/emptychronicle
    pullPolicy: Always
    tag: "git-2a76d3c2352243d8e1aa6315a91f729305e00f63"
  ports:
    port: 5050

  resources:
    requests:
      cpu: 2
      memory: 8Gi

  storage:
    data: 1000Gi

dataProvider:
  enabled: true
  render: true

  storage:
    data: 1000Gi
    log: 10Gi

  image:
    repository: planetariumhq/ninechronicles-dataprovider
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "30"
  db:
    database: ""
    connectionString: ""
    host: ""
    port: 3306
    user: user
    password: ""

explorer:
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-5fffd9a94eac89305cadca9d0fb958ce460f7c69"

  loggingEnabled: true

  # dotnet args

  extraArgs: []
  # - --key=val

  useTurnServer: true

  hosts: []
  #  - "a7ce1613cc0da437c8b06ceb4c4718f4-477884391.us-east-2.elb.amazonaws.com"
  #  - "ab8d1f8ad3c1645a98c57fd27a62531a-728118819.us-east-2.elb.amazonaws.com"

  ports:
    headless: 31234
    graphql: 80

  storage:
    data: 1000Gi
    log: 10Gi

  resources:
    requests:
      cpu: 1
      memory: 6Gi

  nodeSelector:
    beta.kubernetes.io/os: linux
  tolerations: []
  affinity: {}

fullState:
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-5fffd9a94eac89305cadca9d0fb958ce460f7c69"

  loggingEnabled: true

  # dotnet args

  extraArgs: []
  # - --key=val

  useTurnServer: false

  host: "9c-main-full-state.nine-chronicles.com"

  ports:
    headless: 31234
    graphql: 80
    rpc: 31238

  storage:
    data: 1000Gi

  resources:
    requests:
      cpu: 2
      memory: 20Gi

  nodeSelector:
    beta.kubernetes.io/os: linux
  tolerations: []
  affinity: {}

onboardingHeadless:
  enabled: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-5fffd9a94eac89305cadca9d0fb958ce460f7c69"

  # dotnet args

  extraArgs: []
  # - --key=val

  ports:
    headless: 31234
    graphql: 80

  storage:
    data: 1000Gi

  resources:
    requests:
      cpu: 1
      memory: 6Gi

  nodeSelector:
    beta.kubernetes.io/os: linux
  tolerations: []
  affinity: {}

worldBoss:
  enabled: true
  ports:
    targetPort: 5000

  image:
    repository: planetariumhq/world-boss-service
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-05ffdb0f2af019486b3213431031bca5e86a4a3d"

  worldBossEnv:
    databaseUrl: ""
    redisHost: ""
    redisPort: ""
    kmsKeyId: ""
    slackToken: ""
    celeryBrokerUrl: ""
    celeryResultBackend: ""
    slackSigningSecret: ""

bridge:
  enabled: true
  bridgeObserverImage:
    repository: planetariumhq/nine-chronicles-bridge-observer
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-da9637c9ee56051a252f11ff639ed2f0d674afc6"
  bridgeStatusBotImage:
    repository: moreal/bridge-status-bot-alpine
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "20210913-01"

  bridgeEnv:
    privateKey: ""
    mnemonic: ""
    slackBridgeObserverToken: ""
    slackWebToken: ""
    etherscanToken: ""

testHeadless1:
  enabled: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-5fffd9a94eac89305cadca9d0fb958ce460f7c69"

  loggingEnabled: true

  extraArgs: []
  # - --key=val

  useTurnServer: false

  host: "9c-main-test-1.nine-chronicles.com"

  ports:
    headless: 31234
    graphql: 80
    rpc: 31238

  storage:
    data: 1000Gi

  resources:
    requests:
      cpu: 2
      memory: 20Gi

  nodeSelector:
    beta.kubernetes.io/os: linux
  tolerations: []
  affinity: {}

testHeadless2:
  enabled: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-5fffd9a94eac89305cadca9d0fb958ce460f7c69"

  loggingEnabled: true

  extraArgs: []
  # - --key=val

  useTurnServer: false

  host: "9c-main-test-2.nine-chronicles.com"

  ports:
    headless: 31234
    graphql: 80
    rpc: 31238

  storage:
    data: 1000Gi

  resources:
    requests:
      cpu: 2
      memory: 20Gi

  nodeSelector:
    beta.kubernetes.io/os: linux
  tolerations: []
  affinity: {}

marketService:
  enabled: true
  image:
    repository: planetariumhq/market-service
    pullPolicy: Always
    tag: "git-68e6bc82786506b6c89e71f78bafc8d9bed3f23c"

validator:
  count: 8
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-3d04e57f1da46d67ee2ad24109d1f3306c857877"

  consensusSeedStrings:
  - "027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31235"
  - "02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31235"
  - "0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31235"

  hosts:
  - "9c-main-validator-1.nine-chronicles.com"
  - "9c-main-validator-2.nine-chronicles.com"
  - "9c-main-validator-3.nine-chronicles.com"
  - "9c-main-validator-4.nine-chronicles.com"
  - "9c-main-validator-5.nine-chronicles.com"
  - "9c-main-validator-6.nine-chronicles.com"
  - "9c-main-validator-7.nine-chronicles.com"
  - "9c-main-validator-8.nine-chronicles.com"

  ports:
    headless: 31234
    graphql: 80
    gossip: 6000

  # dotnet args

  extraArgs: []
  # - --key=val

  # private keys if not using External Secrets
  privateKeys: []
  # - "<private key>"

  storage:
    data: 1000Gi

  env: []

  resources:
    requests:
      cpu: 2
      memory: 20Gi

  nodeSelector: {}
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "validator"
    effect: "NoSchedule"
  affinity: {}

remoteActionEvaluatorHeadless:
  enabled: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "git-5fffd9a94eac89305cadca9d0fb958ce460f7c69"

  loggingEnabled: true

  extraArgs: []
  # - --key=val

  useTurnServer: true

  host: "9c-main-remote-aev-test.nine-chronicles.com"

  ports:
    headless: 31234
    graphql: 80
    rpc: 31238

  storage:
    data: 1000Gi

  resources:
    requests:
      cpu: 2
      memory: 20Gi

  nodeSelector:
    beta.kubernetes.io/os: linux
  tolerations: []
  affinity: {}

lib9cStateService:
  enabled: false
  image:
    repository: planetariumhq/lib9c-stateservice
    pullPolicy: Always # Overrides the image tag whose default is the chart appVersion.
    tag: "10"

  ports:
    http: 5157

  resources:
    requests:
      cpu: 1

  nodeSelector: {}
  tolerations: []
  affinity: {}
