{{ if .Values.dataProvider.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: data-provider-db
  name: data-provider-db
  namespace: {{ $.Chart.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: data-provider-db
  serviceName: data-provider-db
  template:
    metadata:
      labels:
        app: data-provider-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: data-provider
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: data-provider
          image: mysql:8.0.30
          name: data-provider-db
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data-provider-db-data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: data-provider-db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $.Values.dataProvider.db.storage }}
        storageClassName: {{ $.Chart.Name }}-gp3
        volumeMode: Filesystem
{{ end }}
