apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Chart.Name }}-gp3
parameters:
  fsType: ext4
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: {{ .Values.volumeReclaimPolicy }}
allowVolumeExpansion: true
