apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: empty-chronicle
  labels:
    app: empty-chronicle
    app.kubernetes.io/instance: {{ $.Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empty-chronicle
  serviceName: empty-chronicle
  template:
    metadata:
      labels:
        app: empty-chronicle
      name: empty-chronicle
    spec:
      initContainers:
        - args:
          - https://snapshots.nine-chronicles.com/main/partition
          - /store
          - $(RESET_SNAPSHOT_OPTION)
          - empty-chronicle
          - $(SLACK_WEBHOOK_URL)
          command:
          - /bin/download_snapshot.sh
          image: {{ $.Values.emptyChronicle.image.repository }}:{{ $.Values.emptyChronicle.image.tag }}
          name: reset-snapshot
          volumeMounts:
          - name: download-snapshot-script
            mountPath: /bin/download_snapshot.sh
            readOnly: true
            subPath: download_snapshot.sh
          - mountPath: /store
            name: empty-chronicle-data
          env:
          - name: RESET_SNAPSHOT_OPTION
            value: "true"
          - name: SLACK_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                name: slack
                key: slack-webhook-url
      containers:
        - name: empty-chronicle
          image: "{{ .Values.emptyChronicle.image.repository }}:{{ .Values.emptyChronicle.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.emptyChronicle.ports.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.emptyChronicle.resources | nindent 12 }}
          volumeMounts:
          - name: empty-chronicle-data
            mountPath: /store
      volumes:
      - name: download-snapshot-script
        configMap:
          defaultMode: 0700
          name: {{ $.Chart.Name }}-download-snapshot-script
      nodeSelector:
        eks.amazonaws.com/nodegroup: 9c-main-m7g_2xl_2c_test
      {{- with .Values.emptyChronicle.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumeClaimTemplates:
      - metadata:
          name: empty-chronicle-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: (( $.Values.emptyChronicle.storage.data ))
          storageClassName: {{ $.Chart.Name }}-gp3
          volumeMode: Filesystem
