clusterName: "9c-internal-v2"
logLevel: "debug"

multiplanetary:
  - name: "heimdall"

    genesisBlockPath: "https://planets.nine-chronicles.com/planets/0x000000000001/genesis"

    peerStrings:
    - "029fd8f05609cd98f716ca5245a1ebb85ab52289f9499e8453fa367bded66a945c,tcp-seed-1.heimdall.svc.cluster.local,31234"

    trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

    seed:
      hosts:
      - "tcp-seed-1.heimdall.svc.cluster.local"

      nodeSelector:
        node.kubernetes.io/instance-type: m5d.xlarge

    validator:
      consensusSeedStrings:
      - "029fd8f05609cd98f716ca5245a1ebb85ab52289f9499e8453fa367bded66a945c,tcp-seed-1.heimdall.svc.cluster.local,31235"

      hosts:
      - "heimdall-internal-validator-1.nine-chronicles.com"

      nodeSelector:
        eks.amazonaws.com/nodegroup: heimdall-internal-r7g_l_2c

    remoteHeadless:
      hosts:
      - "heimdall-internal-rpc-1.nine-chronicles.com"
      nodeSelector:
        eks.amazonaws.com/nodegroup: heimdall-internal-r7g_l_2c

    dataProvider:
      nodeSelector:
        eks.amazonaws.com/nodegroup: heimdall-internal-r7g_l_2c

    externalSecret:
      prefix: "9c-internal-v2/heimdall"

    snapshot:
      path: 9c-internal-v2/heimdall
      nodeSelector:
        eks.amazonaws.com/nodegroup: heimdall-internal-r7g_l_2c

    bridgeService:
      enabled: true
      serviceAccount:
        roleArn: "arn:aws:iam::319679068466:role/9c-internal-v2-bridge-service"
      image:
        repository: "planetariumhq/9c-bridge"
        tag: "2023110902"
      nodeSelector:
        node.kubernetes.io/instance-type: m5d.xlarge

    worldBoss: {}
    marketService: {}
    patrolRewardService: {}
    volumeRotator: {}
    acc:
      redis: {}
    emptyChronicle: {}
    lib9cStateService: {}
    remoteActionEvaluatorHeadless: {}
    testHeadless2: {}
    testHeadless1: {}
    explorer: {}
    blockIntervalNotifier: {}
    rudolfService:
      config:
        graphqlEndpoint: "http://heimdall-internal-rpc-1.nine-chronicles.com/graphql"

      kms:
        keyId: "3a301c8e-96c5-4b13-8dee-16575ba637c6"
        publicKey: "04d237239d672698c89fc0788918b4c8610de8b65c5d02ebf3e1f31dcb891683410a97b51f59c05c41c141ad3a05324ba2c5afe32d5e4909e63fd4a700cd36cc53"

      serviceAccount:
        roleArn: "arn:aws:iam::319679068466:role/heimdall-internal-9c-rudolf-signer"

  - name: "idun"

    genesisBlockPath: "https://planets-internal.nine-chronicles.com/planets/0x100000000002/genesis"

    peerStrings:
    - "03380b4ba8722057c9b4d8594f8de9481eb296aba4b3c168666f57b17596452ae7,tcp-seed-1.idun.svc.cluster.local,31234"

    trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

    seed:
      hosts:
      - "tcp-seed-1.idun.svc.cluster.local"

      nodeSelector:
        node.kubernetes.io/instance-type: m5d.xlarge

    validator:
      consensusSeedStrings:
      - "03380b4ba8722057c9b4d8594f8de9481eb296aba4b3c168666f57b17596452ae7,tcp-seed-1.idun.svc.cluster.local,31235"

      hosts:
      - "idun-internal-validator-1.nine-chronicles.com"

      storage: {}

    remoteHeadless:
      hosts:
      - "idun-internal-rpc-1.nine-chronicles.com"
      storage: {}

    externalSecret:
      prefix: "9c-internal-v2/idun"

    snapshot:
      path: 9c-internal-v2/idun

    bridgeService:
      enabled: true
      serviceAccount:
        roleArn: "arn:aws:iam::319679068466:role/9c-internal-v2-bridge-service"
      image:
        repository: "planetariumhq/9c-bridge"
        tag: "2023110902"
      nodeSelector:
        node.kubernetes.io/instance-type: m5d.xlarge

    dataProvider: {}
    worldBoss: {}
    marketService: {}
    patrolRewardService: {}
    volumeRotator: {}
    acc:
      redis: {}
    emptyChronicle: {}
    lib9cStateService: {}
    remoteActionEvaluatorHeadless: {}
    testHeadless2: {}
    testHeadless1: {}
    explorer: {}
    blockIntervalNotifier: {}
    rudolfService:
      config:
        graphqlEndpoint: "https://idun-internal-rpc-1.nine-chronicles.com/graphql"

      kms:
        keyId: "bdf0874e-8ef7-4106-ae62-a721a25af2b9"
        publicKey: "047d28bd576deccc465adcb4d4a82b36d417243c6c11cda9124934e7e41e84c4fa68bb749d2952e949cdd038a73d427367f0cfcb14f85e4c138f78a620a9b6b3e5"

      serviceAccount:
        roleArn: "arn:aws:iam::319679068466:role/idun-internal-9c-rudolf-signer"

global:
  image:
    repository: longfin/9c-headless
    tag: "git-187ab1d0025773afbd926390de4982413780e9c1"

  appProtocolVersion: "200071/AB2da648b9154F2cCcAFBD85e0Bc3d51f97330Fc/MEUCIQCjmCK+qUHtgiVfmFIO+uBw.mI4Kpj9T20U4xdIK8I+MgIgSZPL7qAAplhILfRgXwUSDjjfQgQ7A8jgGNqzwDe+h3I=/ZHU5OnRpbWVzdGFtcHUxMDoyMDIzLTA5LTAxZQ=="

  iceServers: []

  networkType: Default
  consensusType: pbft
  
  resetSnapshot: false
  slackToken: ""
  slackWebHookUrl: ""

externalSecret:
  enabled: true
