clusterName: "9c-internal-v2"
logLevel: "debug"

multiplanetary:
  - name: "heimdall"

    genesisBlockPath: "https://planets.nine-chronicles.com/planets/0x000000000001/genesis"

    peerStrings:
    - "029fd8f05609cd98f716ca5245a1ebb85ab52289f9499e8453fa367bded66a945c,tcp-seed-1.heimdall.svc.cluster.local,31234"

    trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

    seed:
      hosts:
      - "tcp-seed-1.heimdall.svc.cluster.local"

      nodeSelector:
        node.kubernetes.io/instance-type: m5d.xlarge

    validator:
      consensusSeedStrings:
      - "029fd8f05609cd98f716ca5245a1ebb85ab52289f9499e8453fa367bded66a945c,tcp-seed-1.heimdall.svc.cluster.local,31235"

      hosts:
      - "heimdall-internal-validator-1.nine-chronicles.com"

      storage: {}

    remoteHeadless:
      hosts:
      - "heimdall-internal-rpc-1.nine-chronicles.com"
      storage: {}

    externalSecret:
      prefix: "9c-internal-v2/heimdall"

    snapshot:
      path: 9c-internal-v2/heimdall

    bridgeService:
      enabled: true
      serviceAccount:
        roleArn: "arn:aws:iam::319679068466:role/9c-internal-v2-bridge-service"
      image:
        repository: "longfin/araya"
        tag: "2023110901"
      nodeSelector:
        node.kubernetes.io/instance-type: m5d.xlarge

  - name: "idun"

    genesisBlockPath: "https://planets.nine-chronicles.com/planets/0x000000000002/genesis"

    peerStrings:
    - "03380b4ba8722057c9b4d8594f8de9481eb296aba4b3c168666f57b17596452ae7,tcp-seed-1.idun.svc.cluster.local,31234"

    trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

    seed:
      hosts:
      - "tcp-seed-1.idun.svc.cluster.local"

      nodeSelector:
        node.kubernetes.io/instance-type: m5d.xlarge

    validator:
      consensusSeedStrings:
      - "03380b4ba8722057c9b4d8594f8de9481eb296aba4b3c168666f57b17596452ae7,tcp-seed-1.idun.svc.cluster.local,31235"

      hosts:
      - "idun-internal-validator-1.nine-chronicles.com"

      storage: {}

    remoteHeadless:
      hosts:
      - "idun-internal-rpc-1.nine-chronicles.com"
      storage: {}

    externalSecret:
      prefix: "9c-internal-v2/idun"

    snapshot:
      path: 9c-internal-v2/idun

    bridgeService:
      enabled: true
      serviceAccount:
        roleArn: "arn:aws:iam::319679068466:role/9c-internal-v2-bridge-service"
      image:
        repository: "longfin/araya"
        tag: "2023110201"
      nodeSelector:
        node.kubernetes.io/instance-type: m5d.xlarge

global:
  image:
    repository: longfin/9c-headless
    tag: "multiplanetary-2023110801"

  appProtocolVersion: "200071/AB2da648b9154F2cCcAFBD85e0Bc3d51f97330Fc/MEUCIQCjmCK+qUHtgiVfmFIO+uBw.mI4Kpj9T20U4xdIK8I+MgIgSZPL7qAAplhILfRgXwUSDjjfQgQ7A8jgGNqzwDe+h3I=/ZHU5OnRpbWVzdGFtcHUxMDoyMDIzLTA5LTAxZQ=="

  iceServers: []

  networkType: Default
  consensusType: pbft
  
  resetSnapshot: false
  slackToken: ""
  slackWebHookUrl: ""

externalSecret:
  enabled: true
