apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    component: portal
  namespace: {{ .Release.Name }}
spec:
  replicas: {{ .Values.portalService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: portal
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: portal
    spec:
      containers:
        - name: {{ .Values.portalService.name }}
          image: "{{ .Values.portalService.image.repository }}:{{ .Values.portalService.image.tag }}"
          imagePullPolicy: {{ .Values.portalService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.portalService.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets
          resources:
            {{- toYaml .Values.portalService.resources | nindent 12 }}
