apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Release.Name }}-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    - extract:
        key: {{ .Values.portal.externalSecret.prefix }}/env  
