externalSecretKey: ragnarok-breaker/staging

server:
  enabled: true
  image:
    repository: planetariumhq/ragnarok-breaker
    tag: server-6bb4174878d359842fa9e6384ee13fce61911333
  hostname: ragnarok-breaker.9c.gg
