externalSecretKey: ragnarok-breaker/staging

server:
  enabled: true
  image:
    repository: planetariumhq/ragnarok-breaker
    tag: server-2e2d378852b2aacd4a3b58185f0564943c3974fd
  hostname: ragnarok-breaker.9c.gg
