apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.slack: bot-test
spec:
  project: default
  source:
    repoURL: https://github.com/planetarium/9c-infra.git
    targetRevision: main
    path: charts/kong-gateway
    helm:
      valueFiles:
        - ../../srdg/kong-gateway/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-gateway
