clusterName: 9c-internal
provider: RKE2
RKE2:
  domain: rke2.planetarium.network
  publicIPs:
    - 49.247.14.112/32
argocd:
  domain: argocd-internal.planetarium.network
externalSecrets:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::319679068466:role/gke-9c-internal-external-secrets
externalDns:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::319679068466:role/gke-external-dns
certManager:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::319679068466:role/gke-external-dns
  dnsNames:
    - "*.nine-chronicles.com"
    - "*.planetarium.network"
    - "*.planetarium.team"
    - "*.9c.gg"
    - "*.petpop.fun"
    - "*.libplanet.io"
  issuer:
    email: devops@planetariumhq.com
traefik:
  service:
    loadBalancerIP: 49.247.14.112
  nodeSelector:
    node.kubernetes.io/type: general
    node.kubernetes.io/node-index: "1"
  trustedIPs:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 49.247.0.0/16
  - 115.68.0.0/16
  ports:
    postgresql:
      port: 5432
      transport:
        respondingTimeouts:
          readTimeout: 0
    redis:
      port: 6379 
      transport:
        respondingTimeouts:
          readTimeout: 0
    rmq:
      port: 5672
      transport:
        respondingTimeouts:
          readTimeout: 0
    mongodb:
      port: 27017
      transport:
        respondingTimeouts:
          readTimeout: 0
grafana:
  hosts:
    - monitoring-internal.planetarium.network
prometheus:
  server:
    extraScrapeConfigs:
      - job_name: scrape-headlesses
        metrics_path: /metrics
        scrape_interval: 8s
        scrape_timeout: 6s
        static_configs:
