externalSecret:
  enabled: true
  prefix: "mothership-testnet"

env:
  L1_RPC: https://ethereum-holesky-rpc.publicnode.com
  L1_BEACON_RPC: https://ethereum-holesky-beacon-api.publicnode.com

storageClassName: gp3-extensible
awsLoadBalancerSslCert: arn:aws:acm:us-east-2:319679068466:certificate/dbb84b9a-cb2b-407c-924a-70b3ca29e880

genesis:
  source: https://mothership-devnet-holesky-genesis.s3.us-east-2.amazonaws.com/testnet
  createSnapshot: true
  s3SnapshotPath: "mothership-devnet-holesky-genesis/testnet/snapshot"

blockscout:
  loadBalancerExternal: true
  db:
    storage: 100Gi

sequencer:
  enabled: true
  nodeIndex: "1"
  scheme: "http"
  host: "node-1"
  port:
    geth: 8545
    node: 8547

node:
  count: 2
  loadBalancerExternal: true
  hosts:
    - node-1.testnet.holesky.tests.mothership-pla.net
    - node-2.testnet.holesky.tests.mothership-pla.net
  opGeth:
    image: ghcr.io/planetarium/op-geth:latest
    resources:
      requests:
        memory: 4Gi
    extraArgs:
      - "--override.fjord=1717113600"

bundler:
  enabled: true
  gethRpc: http://node-1:8545
  entryPointContract: "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
