apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../common/argocd
  - bootstrap.yaml
  - argocd-secrets.yaml
  - argocd-secret-store.yaml
  - argocd-ingress.yaml
patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-cmd-params-cm.yaml
patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: kubernetes-external-secrets
    patch: |-
      - op: add
        path: /spec/source/helm/values
        value: |-
          env:
            AWS_REGION: ''
            AWS_DEFAULT_REGION: ''
            VAULT_ADDR: ''
          serviceAccount:
            create: true
            name: mothership-external-secrets
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::319679068466:role/eks-mothership-external-secrets
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-dex-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: argo-workflows-sso
              key: client-secret

