{{ if and .Values.marketService.enabled .Values.marketService.rwMode }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: market-service-write
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: market-service-write
  namespace: {{ $.Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-service-write
  serviceName: market-service-write
  template:
    metadata:
      labels:
        app: market-service-write
    spec:
      containers:
        - args:
            - MarketService.dll
          command:
            - dotnet
          env:
            - name: ConnectionStrings__MARKET
              valueFrom:
                secretKeyRef:
                  key: connection-string
                  name: market-db
          {{- with $.Values.marketService.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ $.Values.marketService.image.repository }}:{{ $.Values.marketService.image.tag }}
          name: market-service-write
          ports:
            - containerPort: 80
      {{- with $.Values.marketService.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      {{- with $.Values.marketService.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
  updateStrategy:
    type: RollingUpdate
{{ end }}
