{{ if and .Values.mimir.enabled .Values.mimir.gql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mimir-gql
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: mimir-gql
  namespace: {{ $.Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir-gql
  template:
    metadata:
      labels:
        app: mimir-gql
    spec:
      containers:
        - name: mimir-gql
          image: {{ $.Values.mimir.gql.image.repository }}:{{ $.Values.mimir.gql.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: Database__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: MONGO_DB_CONNECTION_STRING
            - name: RateLimit__PermitLimit
              value: "500"
            - name: RateLimit__Window
              value: "60"
            - name: RateLimit__ReplenishmentPeriod
              value: "60"
            - name: RateLimit__QueueLimit
              value: "5"
            - name: RateLimit__SegmentsPerWindow
              value: "12"
            - name: RateLimit__TokenLimit
              value: "500"
            - name: RateLimit__TokensPerPeriod
              value: "500"
            - name: WncgApi__ApiKeys__0
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: WNCGAPI_APIKEYS_0
            - name: WncgApi__ApiKeys__1
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: WNCGAPI_APIKEYS_1
            - name: WncgApi__ApiKeys__2
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: WNCGAPI_APIKEYS_2
            - name: WncgApi__ApiKeys__3
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: WNCGAPI_APIKEYS_3
            - name: WncgApi__ApiKeys__4
              valueFrom:
                secretKeyRef:
                  name: mimir
                  key: WNCGAPI_APIKEYS_4
            - name: Database__Database
              value: "{{ $.Values.mimir.planetType }}"
          {{- with $.Values.mimir.gql.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      {{- with $.Values.mimir.gql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    type: RollingUpdate
{{ end }}
