{{ if .Values.patrolRewardService.db.local }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: patrol-reward-db
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: patrol-reward-db
  namespace: {{ $.Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patrol-reward-db
  serviceName: patrol-reward-db
  template:
    metadata:
      labels:
        app: patrol-reward-db
    spec:
      containers:
        - env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: database
                name: patrol-reward
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: patrol-reward
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: patrol-reward
          image: postgres:13.3
          name: patrol-reward-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: patrol-reward-db-data
      restartPolicy: Always
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: patrol-reward-db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $.Values.patrolRewardService.db.size }}
        storageClassName: {{ $.Release.Name }}-gp3
        volumeMode: Filesystem
{{ end }}
