{{ if .Values.marketService.enabled }}
{{ if .Values.global.useExternalSecret }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: market-db
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: market-db
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.clusterName }}/market-db
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: market-db
  namespace: {{ $.Release.Name }}
stringData:
  database: {{ .Values.marketService.db.database }}
  user: {{ .Values.marketService.db.user }}
  connection-string: {{ .Values.marketService.db.connectionString }}
type: Opaque
{{ end }}
{{ end }}
