{{ if .Values.dataProvider.enabled }}
{{ if .Values.externalSecret.enabled }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: data-provider
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: data-provider
    creationPolicy: Owner
  dataFrom:
  - extract:
      {{- if .Values.externalSecret.prefix }}
      key: {{ .Values.externalSecret.prefix }}{{ .Values.externalSecret.separator }}data-provider
      {{- else }}
      key: {{ .Values.clusterName }}{{ .Values.externalSecret.separator }}data-provider
      {{- end }}
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: data-provider
  namespace: {{ $.Release.Name }}
stringData:
  database: {{ .Values.dataProvider.db.database }}
  read-host: {{ .Values.dataProvider.db.readHost }}
  read-value: {{ .Values.dataProvider.db.readValue }}
  write-host: {{ .Values.dataProvider.db.writeHost }}
  write-value: {{ .Values.dataProvider.db.writeValue }}
  port: {{ .Values.dataProvider.db.port }}
  user: {{ .Values.dataProvider.db.user }}
  token: {{ .Values.dataProvider.db.token }}
type: Opaque
{{ end }}
{{ end }}
