{{ if .Values.seasonpass.enabled }}
{{ if .Values.externalSecret.enabled }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: seasonpass-env
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: seasonpass-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      {{- if .Values.externalSecret.prefix }}
      key: {{ .Values.externalSecret.prefix }}/seasonpass-env
      {{- else }}
      key: {{ .Values.clusterName }}/seasonpass-env
      {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: seasonpass-env
  namespace: {{ $.Release.Name }}
stringData:
  region: {{ .Values.seasonpass.env.region }}
  gql-url: {{ .Values.seasonpass.env.gqlUrl }}
  current-planet: {{ .Values.seasonpass.env.currentPlanet }}
  db-uri: {{ .Values.seasonpass.env.dbUri }}
  sqs-url: {{ .Values.seasonpass.env.sqsUrl }}
  arena-service-jwt-public-key: {{ .Values.seasonpass.env.arenaServiceJwtPublicKey }}
  adv-boss-sqs-url: ""
  world-clear-sqs-url: ""
type: Opaque
{{- end }}
{{- end }}
