apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 9c-external-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/planetarium/9c-infra.git
    targetRevision: main
    path: charts/external-services
    helm:
      valueFiles:
        - ../../rke2-9c-internal/external-services/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: 9c-external-services
