apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-download-snapshot-script
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
data:
  download_snapshot.sh: |-
    #!/usr/bin/env bash
    
    cd /data
    
    until apt-get -y update
    do
      echo "Try again"
    done
    
    until apt-get -y install curl jq wget aria2 sudo zip
    do
      echo "Try again"
    done
    
    base_url=${1:-https://snapshots.nine-chronicles.com/{{ $.Values.snapshot.path }}}
    save_dir=${2:-"9c-main-snapshot_$(date +%Y%m%d_%H)"}
    download_option=$3
    service_name=$4
    mainnet_snapshot_json_filename="mainnet_latest.json"
    snapshot_zip_filename="state_latest.zip"
    
    if [ $download_option = "true" ]
    then
      echo "Start download snapshot"
      if [ $service_name != "snapshot" ]
      then
        echo $service_name
      fi
    
      # strip tailing slash
      base_url=${base_url%/}
      snapshot_zip_url="$base_url/$snapshot_zip_filename"
    
      echo "$snapshot_zip_url"
      aria2c "$snapshot_zip_url" -j10 -x10 --continue=true
      echo "Unzipping $snapshot_zip_filename"
      unzip -o "$snapshot_zip_filename" -d "$save_dir"
    fi
