externalSecret:
  enabled: true
  prefix: "mothership-devnet"

env:
  L1_RPC: https://ethereum-holesky-rpc.publicnode.com
  L1_BEACON_RPC: https://ethereum-holesky-beacon-api.publicnode.com

storageClassName: gp3-extensible
awsLoadBalancerSslCert: arn:aws:acm:ap-northeast-2:319679068466:certificate/3a295c76-66ac-433d-8448-758c83d374d3

genesis:
  source: https://mothership-devnet-holesky-genesis.s3.us-east-2.amazonaws.com
  createSnapshot: false
  s3SnapshotPath: mothership-devnet-holesky-genesis/snapshot

blockscout:
  loadBalancerExternal: true
  db:
    storage: 100Gi

sequencer:
  enabled: false
  scheme: "https"
  host: "node-1.us-east-2.holesky.tests.mothership-pla.net"
  port:
    node: 8547

node:
  count: 2
  loadBalancerExternal: true
  opNode:
    port:
      p2p:
        tcp: 9003
        udp: 9222
  opGeth:
    port:
      p2p:
        tcp: 30303
        udp: 30304
    resources:
      requests:
        memory: 4Gi
  hosts:
    - node-1.ap-northeast-2.holesky.tests.mothership-pla.net
    - node-2.ap-northeast-2.holesky.tests.mothership-pla.net
