{{ range $idx := until (int .Values.miner.count) }}
{{ $index := add $idx 1 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: miner-{{ $index }}
  name: miner-{{ $index }}
  namespace: {{ $.Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miner-{{ $index }}
  serviceName: miner-{{ $index }}
  template:
    metadata:
      labels:
        app: miner-{{ $index }}
      name: miner-{{ $index }}
    spec:
      containers:
      - args:
        - NineChronicles.Headless.Executable.dll
        - run
        - --workers={{ $.Values.miner.workerCount }}
        - --app-protocol-version={{ $.Values.appProtocolVersion }}
        - --trusted-app-protocol-version-signer={{ $.Values.trustedAppProtocolVersionSigner }}
        - --genesis-block-path={{ $.Values.genesisBlockPath }}
        {{- if $.Values.miner.useTurnServer }}
        {{- range $.Values.iceServers }}
        - --ice-server={{ . }}
        {{- end }}
        {{- else }}
        - --host={{ index $.Values.miner.hosts $idx }}
        {{- end }}
        - --port={{ $.Values.miner.ports.headless }}
        - --store-path=/data/miner
        - --store-type=rocksdb
        - --swarm-private-key
        - $(PRIVATE_KEY)
        - --miner-private-key
        - $(PRIVATE_KEY)
        {{- range $.Values.peerStrings }}
        - --peer={{ . }}
        {{- end }}
        - --graphql-server
        - --graphql-host=0.0.0.0
        - --graphql-port={{ $.Values.miner.ports.graphql }}
        {{- if $.Values.pos.enabled }}
        - --consensus-private-key
        - $(PRIVATE_KEY)
        - --consensus-port={{ $.Values.pos.port }}
        {{- range $.Values.pos.consensusSeedPeerStrings }}
        - --consensus-seed-peer={{ . }}
        {{- end }}
        {{- end }}
        {{- with $.Values.miner.extraArgs }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - --network-type={{ $.Values.networkType }}
        command:
          - dotnet
        env:
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: miner-private-key-{{ $index }}
                name: private-keys
          {{- with $.Values.miner.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        image: {{ $.Values.miner.image.repository }}:{{ $.Values.miner.image.tag }}
        imagePullPolicy: IfNotPresent
        name: miner-{{ $index }}
        ports:
        - containerPort: {{ $.Values.miner.ports.headless }}
          name: headless
          protocol: TCP
        - containerPort: {{ $.Values.miner.ports.graphql }}
          name: graphql
          protocol: TCP
        {{- if $.Values.pos.enabled }}
        - containerPort: {{ $.Values.pos.port }}
          name: gossip
          protocol: TCP
        {{- end }}
        resources:
          {{- toYaml $.Values.miner.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: miner-data-{{ $index }}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: miner-data-{{ $index }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ $.Values.miner.storage.data }}
      storageClassName: {{ $.Chart.Name }}-gp2
      volumeMode: Filesystem
---
{{ end }}
