clusterName: "9c-main-v2"
logLevel: "debug"

multiplanetary:
  - name: "9c-network"

    peerStrings:
    - "027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31234"
    - "02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31234"
    - "0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31234"

    trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

    seed:
      hosts:
      - "9c-main-tcp-seed-1.planetarium.dev"
      - "9c-main-tcp-seed-2.planetarium.dev"
      - "9c-main-tcp-seed-3.planetarium.dev"

      nodeSelector:
        node.kubernetes.io/instance-type: m5d.xlarge

    validator:
      consensusSeedStrings:
      - "027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31235"
      - "02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31235"
      - "0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31235"

      hosts:
      - "9c-main-validator-5.nine-chronicles.com"
      - "9c-main-validator-6.nine-chronicles.com"
      - "9c-main-validator-7.nine-chronicles.com"
      - "9c-main-validator-8.nine-chronicles.com"

    remoteHeadless:
      hosts:
      - "9c-main-rpc-1.nine-chronicles.com"
      - "9c-main-rpc-2.nine-chronicles.com"
      - "9c-main-rpc-3.nine-chronicles.com"
      - "9c-main-rpc-4.nine-chronicles.com"
      - "9c-main-rpc-5.nine-chronicles.com"
      - "9c-main-rpc-6.nine-chronicles.com"
      - "9c-main-rpc-7.nine-chronicles.com"
      - "9c-main-rpc-8.nine-chronicles.com"
      - "9c-main-rpc-9.nine-chronicles.com"
      - "9c-main-rpc-10.nine-chronicles.com"

    snapshot:
      path: 9c-main-v2/main/partition

    bridgeService:
      enabled: true

      nodeSelector:
        node.kubernetes.io/instance-type: m5d.xlarge

    externalSecret: {}
    dataProvider: {}
    worldBoss: {}
    marketService: {}
    patrolRewardService: {}
    volumeRotator: {}
    acc:
      redis: {}
    emptyChronicle: {}
    lib9cStateService: {}
    remoteActionEvaluatorHeadless: {}
    testHeadless2: {}
    testHeadless1: {}
    explorer: {}
    blockIntervalNotifier: {}
    rudolfService: {}

global:
  image:
    repository: planetariumhq/ninechronicles-headless
    tag: "git-28f4aafee9c8b126b3485f17ee7133232711c6a8"

  appProtocolVersion: "200100/AB2da648b9154F2cCcAFBD85e0Bc3d51f97330Fc/MEQCIFrSIu5hDF+iBBRn7kGn20PJCu0v6jpMZkE9fRcKbtgGAiBnzLjwlJtNUQgoI+4HGhdKFvSEQT.iSkqUS458ppZJOQ==/ZHU5OnRpbWVzdGFtcHUxMDoyMDIzLTExLTA3ZQ=="

  genesisBlockPath: "https://release.nine-chronicles.com/genesis-block-9c-main"
  
  iceServers:
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us2.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us3.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us4.planetarium.dev:3478"
  - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us5.planetarium.dev:3478"

  networkType: Main
  consensusType: pbft
  
  resetSnapshot: false
  rollbackSnapshot: false
  slackToken: ""
  slackWebHookUrl: ""

externalSecret:
  enabled: true

volumeReclaimPolicy: "Retain"

blockIntervalNotifier:
  enabled: true
