clusterName: 9c-main
provider: RKE2
RKE2:
  domain: rke2-main.planetarium.network
  publicIPs:
    - 49.247.14.88/32
    - 115.68.199.177/32
argocd:
  domain: argocd.planetarium.network
  cssUrl: https://9c-cluster-config.s3.us-east-2.amazonaws.com/9c-main/css/argocd.css
externalSecrets:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::319679068466:role/gke-9c-internal-external-secrets
externalDns:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::319679068466:role/gke-external-dns
certManager:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::319679068466:role/gke-external-dns
  dnsNames:
    - "nine-chronicles.com"
    - "*.nine-chronicles.com"
    - "nine-chronicles.dev"
    - "*.nine-chronicles.dev"
    - "*.planetarium.network"
    - "*.planetarium.team"
    - "*.9c.gg"
    - "petpop.fun"
    - "*.petpop.fun"
  issuer:
    email: devops@planetariumhq.com
traefik:
  service:
    loadBalancerIP: 115.68.199.177
  nodeSelector:
    node.kubernetes.io/type: baremetal
    node.kubernetes.io/node-index: "1"
  trustedIPs:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 49.247.0.0/16
  - 115.68.0.0/16
loki:
  enabled: true
  bucketName: 9c-loki
  write:
    count: 2
    nodeSelector:
      node.kubernetes.io/type: general
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 2Gi
  read:
    count: 2
    nodeSelector:
      node.kubernetes.io/type: general
    resources:
      requests:
        cpu: 500m
        memory: 4Gi
      limits:
        cpu: 500m
        memory: 4Gi
grafana:
  hosts:
    - monitoring.planetarium.network
prometheus:
  server:
    extraScrapeConfigs:
      - job_name: scrape-headlesses
        metrics_path: /metrics
        scrape_interval: 8s
        scrape_timeout: 6s
        static_configs:
          - labels:
              group: odin-rpc
            targets:
              - remote-headless-1.odin.svc.cluster.local:80
              - remote-headless-2.odin.svc.cluster.local:80
              - remote-headless-3.odin.svc.cluster.local:80
              - odin-node-4.nine-chronicles.com:80
              - odin-node-5.nine-chronicles.com:80
          - labels:
              group: odin-validator
            targets:
              - validator-5.odin.svc.cluster.local:80
          - labels:
              group: heimdall-rpc
            targets:
              - remote-headless-1.heimdall.svc.cluster.local:80
              - remote-headless-2.heimdall.svc.cluster.local:80
          - labels:
              group: heimdall-validator
            targets:
              - validator-5.heimdall.svc.cluster.local:80
datadog:
  enabled: true
  clusterAgent:
    nodeSelector:
      node.kubernetes.io/type: general
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/network
            operator: In
            values:
            - odin
            - heimdall
