apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-dbs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/planetarium/9c-infra.git
    targetRevision: rke2
    path: rke2-9c-internal/common-dbs
  destination:
    server: https://kubernetes.default.svc
    namespace: common-dbs
