apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rmq
    app.kubernetes.io/instance: common-dbs
  name: rmq
  namespace: common-dbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmq
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
        - name: rmq
          image: rabbitmq:3.12-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: RMQ_USERNAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: RMQ_PASSWORD
      restartPolicy: Always
  strategy:
    type: RollingUpdate 