name: Update values
on:
  workflow_dispatch:
    inputs:
      dir:
        required: true
        description: 'Dir'
        default: '9c-internal'
        type: choice
        options:
        - 9c-main
        - 9c-internal
      file-name:
        required: true
        description: 'FileName'
        default: 'general'
        type: choice
        options:
        - general
        - odin
        - heimdall
        - thor
      headless:
        description: 'Dockerhub tag for headless (e.g. 30, git-5db812731f7fef1156b00a90ff0267e95dd31820)'
      seed:
        description: 'Same, for seed'
      bridge-service:
        description: 'Same, bridgeService'
      data-provider:
        description: 'Same, for DP'
      world-boss-service:
        description: 'Same, for world-boss-service'
      market-service:
        description: 'Same, for market-service'
      rudolf-service:
        description: 'Same, for rudolf-service'

jobs:
  update-values-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.10.13

      - run: |
          python -m pip install -r requirements.txt
          flit install
        name: install dependencies
        working-directory: ./scripts

      - name: Update values
        id: update-values
        run: |
          bash .github/scripts/update-values.sh "${{ github.event.inputs.dir }}" "${{ github.event.inputs.file-name }}" "${{ github.event.inputs.headless }}" "${{ github.event.inputs.seed }}" "${{ github.event.inputs.bridge-service }}" "${{ github.event.inputs.data-provider }}" "${{ github.event.inputs.world-boss-service }}" "${{ github.event.inputs.market-service }}" "${{ github.event.inputs.rudolf-service }}"
        env:
          GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
