namespace: "9c-network"

ports:
  targetPort: 5000

image:
  repository: planetariumhq/9c-signer
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "git-8eb59f1c0fe1293302c337819a1ecca7f31aa51d"

db:
  database: ""
  user: ""
  size: 100Gi

useExternalSecret: true

clusterName: 9c-internal-v2

storage:
  class: 9c-network-gp3

nodeSelector:
  node.kubernetes.io/instance-type: m5d.large

serviceAccount:
  create: true
  name: garage-signer
  iamRole: arn:aws:iam::319679068466:role/9c-onboarding-eks

garageSignerEnv:
  databaseUrl: ""
  redisUrl: ""
  kmsKeyId: ""
  celeryBrokerUrl: ""
  celeryResultBackend: ""
